from enum import StrEnum


class UserRole(StrEnum):
    APPLICANT = "APPLICANT"
    VOLUNTEER = "VOLUNTEER"
    ADMIN = "ADMIN"


class TaskCategory(StrEnum):
    PERSONAL_HELP = "PERSONAL_HELP"
    EVENT_ORGANIZATION = "EVENT_ORGANIZATION"
    OTHER = "OTHER"


class TaskStatus(StrEnum):
    PENDING_MODERATION = "PENDING_MODERATION"
    PUBLISHED = "PUBLISHED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
